In [5]:
from sklearn import svm, datasets 
iris = datasets.load_iris ()

In [6]:
import pandas as pd 
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target 
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)      flower
47                4.6               3.2                1.4               0.2      setosa
48                5.3               3.7                1.5               0.2      setosa
49                5.0               3.3                1.4               0.2      setosa
50                7.0               3.2                4.7               1.4  versicolor
51                6.4               3.2                4.5               1.5  versicolor

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=0)

In [14]:
model = svm.SVC(kernel='rbf', C=30, gamma='auto') 
model.fit(X_train, y_train) 
model.score(X_test, y_test)

0.9777777777777777

In [15]:
from sklearn.model_selection import cross_val_score

In [18]:
cross_val_score(svm.SVC(kernel='rbf', C=30, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [19]:
cross_val_score(svm.SVC(kernel='linear', C=30, gamma='auto'), iris.data, iris.target, cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [20]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [21]:
from sklearn.model_selection import GridSearchCV 

clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20], 
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target) 
clf.cv_results_

{'mean_fit_time': array([0.00060287, 0.00040903, 0.00060253, 0.00040879, 0.00103025,
        0.00040216]),
 'std_fit_time': array([4.92240031e-04, 5.00996661e-04, 4.91964947e-04, 5.00779360e-04,
        4.76158135e-05, 4.92548951e-04]),
 'mean_score_time': array([0.00040221, 0.00047278, 0.00040417, 0.        , 0.        ,
        0.00060344]),
 'std_score_time': array([0.00049261, 0.00058997, 0.00049502, 0.        , 0.        ,
        0.0004927 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'li

In [23]:
df = pd.DataFrame(clf.cv_results_)
df 

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0       0.000603      0.000492         0.000402  ...         0.980000        0.016330               1
1       0.000409      0.000501         0.000473  ...         0.980000        0.016330               1
2       0.000603      0.000492         0.000404  ...         0.980000        0.016330               1
3       0.000409      0.000501         0.000000  ...         0.973333        0.038873               4
4       0.001030      0.000048         0.000000  ...         0.966667        0.036515               5
5       0.000402      0.000493         0.000603  ...         0.966667        0.042164               6

[6 rows x 15 columns]

In [24]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [31]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20], 
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False, n_iter=2)

rs.fit(iris.data, iris.target) 
df = pd.DataFrame(rs.cv_results_)
df 

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score std_test_score  rank_test_score
0       0.001112      0.000196         0.000000  ...         0.966667       0.036515                2
1       0.000814      0.000407         0.000254  ...         0.980000       0.016330                1

[2 rows x 15 columns]